# This is a basic workflow to help you get started with Actions

name: Docker Image CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    tags:
    - 'dev-resuit*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env: 
 KUBE_DEPLOYMENT_FILE: ${{ secrets.KUBE_DEPLOYMENT_FILE }}
 ENV_FILE: ${{ secrets.ENV_FILE }}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Create env Files
        run: |
          echo $ENV_FILE >> .env
          cat .env
          pwd 
          ls -a
      # - name: Install kubectl
      #   uses: azure/setup-kubectl@v1
      #   with:
      #     version: 'v1.21.3'
      #   id: installs
      # # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v3
      # - name: docker login
      #   env: 
      #    DOCKER_USER: ${{secrets.DOCKER_USER}}
      #    DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      #   run: |
      #    docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      # - name: Build The docker image
      #   run: docker build -t zneetesh/admin-portal  .
      # - name: Docker push 
      #   run: docker push ${{secrets.DOCKER_USER}}/admin-portal